version: '3'
networks: 
  backend:
    driver: bridge

services:
  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    ports:
      - "9000:9000" 
    volumes:
      - ./php-fpm/php56.ini:/usr/local/etc/php/php.ini
      - ../:/usr/share/nginx/html
      - ./log/project:/var/log/project
    extra_hosts:
      - "dockerhost:10.0.75.1"
    networks:
      - backend
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/usr/share/nginx/html
      - ./log/nginx:/var/log/nginx      
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
    networks:
        - backend
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data:rw"
    command: redis-server
    depends_on:
      - php-fpm
    networks:
        - backend

