version: '3'
networks: 
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    volumes:
      - ./php-fpm/php56.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_ORIGIN}:${APP_CODE_PATH_CONTAINER}
      - ${LOG_PATH_ORIGIN}:${LOG_PATH_CONTAINER}
    expose:
      - "9000" 
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_ORIGIN}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_LOG_PATH_ORIGIN}:${NGINX_LOG_PATH_CONTAINER}     
      - ${NGINX_CONFIG_PATH_ORIGIN}:${NGINX_CONFIG_PATH_CONTAINER}
    depends_on:
      - php-fpm
    networks:
        - frontend
        - backend
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${REDIS_DATA_PATH}/redis:/data:rw"
    command: redis-server
    depends_on:
      - php-fpm
    networks:
      - backend

